[2022-12-14T15:12:57.924+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: incident_etl.etl_incident manual__2022-12-14T15:12:53.628655+00:00 [queued]>
[2022-12-14T15:12:57.940+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: incident_etl.etl_incident manual__2022-12-14T15:12:53.628655+00:00 [queued]>
[2022-12-14T15:12:57.941+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T15:12:57.941+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T15:12:57.941+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T15:12:57.961+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): etl_incident> on 2022-12-14 15:12:53.628655+00:00
[2022-12-14T15:12:57.971+0000] {standard_task_runner.py:55} INFO - Started process 28648 to run task
[2022-12-14T15:12:57.977+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'incident_etl', 'etl_incident', 'manual__2022-12-14T15:12:53.628655+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_incident.py', '--cfg-path', '/tmp/tmpkpo429eb']
[2022-12-14T15:12:57.980+0000] {standard_task_runner.py:83} INFO - Job 78: Subtask etl_incident
[2022-12-14T15:12:58.098+0000] {task_command.py:389} INFO - Running <TaskInstance: incident_etl.etl_incident manual__2022-12-14T15:12:53.628655+00:00 [running]> on host 1f859f359fd5
[2022-12-14T15:12:58.243+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=noe
AIRFLOW_CTX_DAG_ID=incident_etl
AIRFLOW_CTX_TASK_ID=etl_incident
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T15:12:53.628655+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-14T15:12:53.628655+00:00
[2022-12-14T15:12:58.245+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-14T15:12:58.246+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl/etl_incident.py']
[2022-12-14T15:12:58.275+0000] {subprocess.py:86} INFO - Output:
[2022-12-14T15:13:06.279+0000] {subprocess.py:93} INFO - bus_incident.csv création du blob en cours
[2022-12-14T15:13:06.281+0000] {subprocess.py:93} INFO - blob créé
[2022-12-14T15:13:06.282+0000] {subprocess.py:93} INFO - upload du csv vers le blob en cours
[2022-12-14T15:13:06.518+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-12-14T15:13:06.549+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=incident_etl, task_id=etl_incident, execution_date=20221214T151253, start_date=20221214T151257, end_date=20221214T151306
[2022-12-14T15:13:06.935+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-14T15:13:06.966+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
