[2022-12-13T16:25:19.804+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bus_pos_etl.etl_bus_loc manual__2022-12-13T16:25:17.994943+00:00 [queued]>
[2022-12-13T16:25:19.816+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bus_pos_etl.etl_bus_loc manual__2022-12-13T16:25:17.994943+00:00 [queued]>
[2022-12-13T16:25:19.816+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T16:25:19.816+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-13T16:25:19.816+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T16:25:19.832+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): etl_bus_loc> on 2022-12-13 16:25:17.994943+00:00
[2022-12-13T16:25:19.841+0000] {standard_task_runner.py:55} INFO - Started process 706 to run task
[2022-12-13T16:25:19.845+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bus_pos_etl', 'etl_bus_loc', 'manual__2022-12-13T16:25:17.994943+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test_noe_bash.py', '--cfg-path', '/tmp/tmpgsz5b_s6']
[2022-12-13T16:25:19.846+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask etl_bus_loc
[2022-12-13T16:25:19.913+0000] {task_command.py:389} INFO - Running <TaskInstance: bus_pos_etl.etl_bus_loc manual__2022-12-13T16:25:17.994943+00:00 [running]> on host ff6f332d28b5
[2022-12-13T16:25:19.988+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=noe
AIRFLOW_CTX_DAG_ID=bus_pos_etl
AIRFLOW_CTX_TASK_ID=etl_bus_loc
AIRFLOW_CTX_EXECUTION_DATE=2022-12-13T16:25:17.994943+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-13T16:25:17.994943+00:00
[2022-12-13T16:25:19.989+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-13T16:25:19.990+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl/etl.py']
[2022-12-13T16:25:20.004+0000] {subprocess.py:86} INFO - Output:
[2022-12-13T16:25:20.349+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-13T16:25:20.349+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/etl/etl.py", line 5, in <module>
[2022-12-13T16:25:20.350+0000] {subprocess.py:93} INFO -     import geopandas as gpd
[2022-12-13T16:25:20.350+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'geopandas'
[2022-12-13T16:25:20.421+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-13T16:25:20.434+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-13T16:25:20.437+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bus_pos_etl, task_id=etl_bus_loc, execution_date=20221213T162517, start_date=20221213T162519, end_date=20221213T162520
[2022-12-13T16:25:20.457+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task etl_bus_loc (Bash command failed. The command returned a non-zero exit code 1.; 706)
[2022-12-13T16:25:20.500+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-13T16:25:20.529+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
