[2022-12-13T17:05:48.065+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: incident_etl.etl_incident manual__2022-12-13T17:05:43.124894+00:00 [queued]>
[2022-12-13T17:05:48.084+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: incident_etl.etl_incident manual__2022-12-13T17:05:43.124894+00:00 [queued]>
[2022-12-13T17:05:48.085+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T17:05:48.085+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-13T17:05:48.085+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-13T17:05:48.102+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): etl_incident> on 2022-12-13 17:05:43.124894+00:00
[2022-12-13T17:05:48.113+0000] {standard_task_runner.py:55} INFO - Started process 2687 to run task
[2022-12-13T17:05:48.118+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'incident_etl', 'etl_incident', 'manual__2022-12-13T17:05:43.124894+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_incident.py', '--cfg-path', '/tmp/tmplxmenen8']
[2022-12-13T17:05:48.120+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask etl_incident
[2022-12-13T17:05:48.218+0000] {task_command.py:389} INFO - Running <TaskInstance: incident_etl.etl_incident manual__2022-12-13T17:05:43.124894+00:00 [running]> on host ff6f332d28b5
[2022-12-13T17:05:48.306+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=noe
AIRFLOW_CTX_DAG_ID=incident_etl
AIRFLOW_CTX_TASK_ID=etl_incident
AIRFLOW_CTX_EXECUTION_DATE=2022-12-13T17:05:43.124894+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-13T17:05:43.124894+00:00
[2022-12-13T17:05:48.307+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-13T17:05:48.308+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl/etl_incident.py']
[2022-12-13T17:05:48.328+0000] {subprocess.py:86} INFO - Output:
[2022-12-13T17:05:49.769+0000] {subprocess.py:93} INFO - bus_incident.csv création du blob en cours
[2022-12-13T17:05:49.770+0000] {subprocess.py:93} INFO - blob créé
[2022-12-13T17:05:49.770+0000] {subprocess.py:93} INFO - upload du csv vers le blob en cours
[2022-12-13T17:05:50.007+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2022-12-13T17:05:50.080+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=incident_etl, task_id=etl_incident, execution_date=20221213T170543, start_date=20221213T170548, end_date=20221213T170550
[2022-12-13T17:05:50.139+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-13T17:05:50.172+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
