[2022-12-14T11:16:57.948+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bus_pred_etl.etl_bus_pred scheduled__2022-12-13T00:00:00+00:00 [queued]>
[2022-12-14T11:16:57.966+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: bus_pred_etl.etl_bus_pred scheduled__2022-12-13T00:00:00+00:00 [queued]>
[2022-12-14T11:16:57.966+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T11:16:57.966+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T11:16:57.966+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T11:16:57.985+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): etl_bus_pred> on 2022-12-13 00:00:00+00:00
[2022-12-14T11:16:57.995+0000] {standard_task_runner.py:55} INFO - Started process 16702 to run task
[2022-12-14T11:16:58.000+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bus_pred_etl', 'etl_bus_pred', 'scheduled__2022-12-13T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl_bus_pred.py', '--cfg-path', '/tmp/tmpui3zypla']
[2022-12-14T11:16:58.003+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask etl_bus_pred
[2022-12-14T11:16:58.109+0000] {task_command.py:389} INFO - Running <TaskInstance: bus_pred_etl.etl_bus_pred scheduled__2022-12-13T00:00:00+00:00 [running]> on host 1f859f359fd5
[2022-12-14T11:16:58.288+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=noe
AIRFLOW_CTX_DAG_ID=bus_pred_etl
AIRFLOW_CTX_TASK_ID=etl_bus_pred
AIRFLOW_CTX_EXECUTION_DATE=2022-12-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-13T00:00:00+00:00
[2022-12-14T11:16:58.290+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-14T11:16:58.291+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/etl/etl_bus_pred.py']
[2022-12-14T11:16:58.312+0000] {subprocess.py:86} INFO - Output:
[2022-12-14T11:17:03.418+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2022-12-14T11:17:03.419+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/etl/etl_bus_pred.py", line 51, in <module>
[2022-12-14T11:17:03.419+0000] {subprocess.py:93} INFO -     load_to_gcs(extract_API())
[2022-12-14T11:17:03.419+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/etl/etl_bus_pred.py", line 33, in extract_API
[2022-12-14T11:17:03.419+0000] {subprocess.py:93} INFO -     df = json_normalize(data_dict["Predictions"])
[2022-12-14T11:17:03.419+0000] {subprocess.py:93} INFO - KeyError: 'Predictions'
[2022-12-14T11:17:03.582+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2022-12-14T11:17:03.594+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-12-14T11:17:03.598+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=bus_pred_etl, task_id=etl_bus_pred, execution_date=20221213T000000, start_date=20221214T111657, end_date=20221214T111703
[2022-12-14T11:17:03.623+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 55 for task etl_bus_pred (Bash command failed. The command returned a non-zero exit code 1.; 16702)
[2022-12-14T11:17:03.822+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-14T11:17:03.855+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
